print('  ' + '-'*(48) + '-')
print(" |                                                 |")
print(" |    01Hello                                      |")
print(" |    Name : Aditi                                 |")
print(" |    Version: 01                                  |")
print(" |                                                 |")
print('  ' + '-'*(48) + '-')
print("Hello World")