print(' -' + '-'*(46) + '-')
print("|                                                |")
print("|    01GoodbyeWorld                              |")
print("|    Name : Aditi                                |")
print("|    Version : 01                                |")
print("|                                                |")
print(' -' + '-'*(46) + '-')
print("Hello")
name = input("What is your name ?")
print("Goodbye", name)
