print(' -' + '-'*(46) + '-')
print("|                                                |")
print("|    03GoodbyePerson                             |")
print("|    Name : Aditi                                |")
print("|    Version : 01                                |")
print("|                                                |")
print(' -' + '-'*(46) + '-')
print("Hello")
name = input("What is your name ? ")
print("Goodbye", name)
